name: Trigger auto deployment for novacloud-api

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/novacloud-api-AutoDeployTrigger-99d55602-5a97-4621-a9b3-53980fa9fb9d.yml"

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.NOVACLOUDAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NOVACLOUDAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NOVACLOUDAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build, push and deploy backend
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: backend/CloudService.WebApi/Dockerfile
          registryUrl: docker.io
          registryUsername: ${{ secrets.NOVACLOUDAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NOVACLOUDAPI_REGISTRY_PASSWORD }}
          containerAppName: novacloud-api
          resourceGroup: rg-novacloud
          imageToBuild: docker.io/lethanhtran/novacloud-api:${{ github.sha }}